excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://whitingx.github.io
title: ElectronicPress
tagline: User Experience Design & Research
description: Information & links relating to Product Design, User Experience (UX) & Typography from <a href="https://twitter.com/whitingx">Rob Whiting</a>
paginate: 5
gems:
  - jekyll-seo-tag
