excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://whitingx.github.io
title: Electronicpress
tagline: User Experience Design & Research
description: My awesome new site
paginate: 5