excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://whitingx.github.io
title: ElectronicPress
tagline: User Experience Design & Research
description: Information & links relating to Design, Research, UX & Typography from <a href="https://www.linkedin.com/in/whitingx/">Rob Whiting</a>
paginate: 5
gems:
  - jekyll-seo-tag
